### ISSUE TITLE
agamy is lazy 

### ISSUE THREAD

**Issue by kar66-star** [kar66-star/test-#3]
**agamy doesn't wakeup early he is so lazy.**

**expected outcome:**
agamy wakeup early

**actual outcome:**
he sleeps till night 

*****steps to reproduce:**
1-eat well 
2-sleep at 10 
3-make an alarm
affected files:
el sherka **bazet**
**---recommendations:**
3ala allah

**Comment by agamyii** [comment]
No mann agamy wakes up early!

**Comment by agamyii** [comment]
Agamy Love Keita
